---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$CHgxxrnu0TYkoxW5$Y7LhIK2afy5lq412359QJALAXf6lulo9.VN22Bx7SiHtsqFcBQTAGM5W7XJEPSIgzY2GDkaNFdQfxc3QFDnM81"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$6$YicZOCLhtnxdi$1VcpIqpkCEnPnYpzqFHSXPZbpg6.hf5T9m7ZhdhTOAZ4wwhVk3sb.fkt6578GdAq3D5GuccnQOoOgsiUjLyXJ/"
# Cloud Vision server information
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: ''
# cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.2

# dns servers.
name_servers:
  - 192.168.0.2
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - 0.jp.pool.ntp.org
  - 1.jp.pool.ntp.org
